export enum ActionType {
    FILTER = 'FILTER',
    FILTERALL = 'FILTERALL',
    SORT = 'SORT',
    FETCH_SEARCH_ID = 'FETCH_SEARCH_ID',
    FETCH_TICKETS = 'FETCH_TICKETS',
    LOADING = 'LOADING',
    SHOW_MORE = 'SHOW_MORE'
}
